// Generated by ReScript, PLEASE EDIT WITH CARE


async function run(preferences) {
  let res = await preferences.get({
    key: "pokebook_state"
  });
  let json = res.value;
  if (json !== null) {
    return Promise.resolve(json);
  } else {
    return Promise.resolve("{}");
  }
}

export {
  run,
}
/* No side effect */
