// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Preferences from "../adapters/Preferences.res.mjs";

async function loadState() {
  let res = await Preferences.get({
    key: "pokebook_state"
  });
  let json = res.value;
  if (json !== null) {
    return Promise.resolve(json);
  } else {
    return Promise.resolve("{}");
  }
}

export {
  loadState,
}
/* No side effect */
