// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Preferences from "../adapters/Preferences.res.mjs";

async function loadState() {
  let res = await Preferences.get({
    key: "pokebook_state"
  });
  let json = res.value;
  if (json === null) {
    return Promise.resolve("{}");
  } else {
    return Promise.resolve(json);
  }
}

async function saveState(value) {
  await Preferences.set({
    key: "pokebook_state",
    value: value
  });
  return Promise.resolve();
}

export {
  loadState,
  saveState,
}
/* No side effect */
