// Generated by ReScript, PLEASE EDIT WITH CARE

import * as YjsPoemDoc from "./adapters/YjsPoemDoc/YjsPoemDoc.res.mjs";

let doc = YjsPoemDoc.make();

doc.transact(() => {
  let t = doc.name();
  t.insert(0, "hello");
});

console.log(doc.name().toString());

export {
  doc,
}
/* doc Not a pure module */
