// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Yjs from "yjs";

function makeYLikeText(t) {
  return {
    insert: (i, s) => {
      t.insert(i, s);
    },
    delete: (i, len) => {
      t.delete(i, len);
    },
    length: () => t.length,
    toString: () => t.toString()
  };
}

function make() {
  let doc = new Yjs.Doc();
  let s_nameText = doc.getText("title");
  let s_poemText = doc.getText("poem");
  let s_noteText = doc.getText("note");
  let transact = fn => {
    doc.transact(_tx => fn());
  };
  return {
    name: () => makeYLikeText(s_nameText),
    text: () => makeYLikeText(s_poemText),
    note: () => makeYLikeText(s_noteText),
    transact: transact
  };
}

export {
  make,
}
/* yjs Not a pure module */
