// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Yjs from "yjs";

function make() {
  let doc = new Yjs.Doc();
  let nameText = doc.getText("title");
  let poemText = doc.getText("poem");
  let noteText = doc.getText("note");
  return {
    doc: doc,
    nameText: nameText,
    poemText: poemText,
    noteText: noteText
  };
}

function name(self) {
  return self.nameText;
}

function text(self) {
  return self.poemText;
}

function note(self) {
  return self.noteText;
}

function transact(self, fn) {
  self.doc.transact(fn);
}

export {
  make,
  name,
  text,
  note,
  transact,
}
/* yjs Not a pure module */
