// Generated by ReScript, PLEASE EDIT WITH CARE


function plugin_get(param) {
  return Promise.resolve({
    value: localStorage.getItem(param.key)
  });
}

function plugin_set(param) {
  localStorage.setItem(param.key, param.value);
  return Promise.resolve();
}

function plugin_remove(param) {
  localStorage.removeItem(param.key);
  return Promise.resolve();
}

function plugin_clear() {
  localStorage.clear();
  return Promise.resolve();
}

let plugin = {
  get: plugin_get,
  set: plugin_set,
  remove: plugin_remove,
  clear: plugin_clear
};

export {
  plugin,
}
/* No side effect */
