// Generated by ReScript, PLEASE EDIT WITH CARE


function make() {
  return {
    get: param => Promise.resolve({
      value: localStorage.getItem(param.key)
    }),
    set: param => {
      localStorage.setItem(param.key, param.value);
      return Promise.resolve();
    },
    remove: param => {
      localStorage.removeItem(param.key);
      return Promise.resolve();
    },
    clear: () => {
      localStorage.clear();
      return Promise.resolve();
    }
  };
}

export {
  make,
}
/* No side effect */
