// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function getWindow() {
  return Primitive_option.fromNullable(globalThis.window);
}

function hasWindow() {
  return Stdlib_Option.isSome(Primitive_option.fromNullable(globalThis.window));
}

function isTauri() {
  let win = Primitive_option.fromNullable(globalThis.window);
  if (win !== undefined) {
    return Stdlib_Option.isSome(Primitive_option.fromNullable(Primitive_option.valFromOption(win).__TAURI_INTERNALS__));
  } else {
    return false;
  }
}

async function loadPreferencesWeb() {
  return await import("./PreferencesWeb.res.mjs").then(m => m.plugin);
}

let implPromise = {
  contents: undefined
};

function loadImpl() {
  let p = implPromise.contents;
  if (p !== undefined) {
    return p;
  }
  let p$1 = Stdlib_Option.isSome(Primitive_option.fromNullable(globalThis.window)) ? (
      isTauri() ? Promise.reject({
          RE_EXN_ID: "Failure",
          _1: "Preferences: Tauri adapter not implemented"
        }) : loadPreferencesWeb()
    ) : Promise.reject({
      RE_EXN_ID: "Failure",
      _1: "Preferences: window is not available (SSR import?)"
    });
  implPromise.contents = p$1;
  return p$1;
}

function withImpl(f) {
  return loadImpl().then(f);
}

function api_get(opts) {
  return loadImpl().then(impl => impl.get(opts));
}

function api_set(opts) {
  return loadImpl().then(impl => impl.set(opts));
}

function api_remove(opts) {
  return loadImpl().then(impl => impl.remove(opts));
}

function api_clear() {
  return loadImpl().then(impl => impl.clear());
}

let api = {
  get: api_get,
  set: api_set,
  remove: api_remove,
  clear: api_clear
};

export {
  getWindow,
  hasWindow,
  isTauri,
  loadPreferencesWeb,
  implPromise,
  loadImpl,
  withImpl,
  api,
}
/* No side effect */
